public class DemoClass {
    
    public void Save(){
        //long now=datetime.now().gettime();
        //while(datetime.now().gettime()-now <10000);
        
        //PageReference redirectPage = new PageReference('/0012w000003o1WmAAI');
        //return redirectPage;
      DEmoClass2 dm = new DEmoClass2();
      dm.method();
        dm.method2();
       // system.debug('a=='+ dm.a);
    }

    public void Save3(){
        Save2();
    }
    public void Save2(){

    }
}